//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThinkTankerClasses.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThinkTankerClasses.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Two numbers are in the ratio 5:8. If the difference is 36, what is the larger of the two numbers?&quot;,96
        ///&quot;A train travels 60 km in ¾ hour. If it maintains the same average speed, how far will it travel in 2 ½ hours?&quot;,200
        ///A piece of rope 75 meters long is cut into three pieces in the ratio 4:5:6. How long is the longest piece?,30
        ///A man left home by bus at 8:15 AM and reached a town 45 km away at 9:45. What was his average speed per hour to the nearest kilometer?,30
        ///&quot;One man can dig a hole 2 meters x 2 mete [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string difficult {
            get {
                return ResourceManager.GetString("difficult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;If a car travels at a speed of 60 km/h for 4 hours, how far will it have traveled in km?&quot;,240
        ///&quot;A farmer harvested 109 cavans of palay from his field. If each cavan sold for? 350, how much did he get?&quot;,38150
        ///Three more than 6 times a number is 45. What is the number.,7
        ///&quot;Erl is 3 years older than Dhang. Together, their ages total 21 years. How old is Erl?&quot;,12
        ///&quot;Joy bought 4 mangoes for? 46. At the same rate, how much would a dozen cost?&quot;,138
        ///&quot;If I multiply a number by 8 and then subtract 15 from the prod [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string easy {
            get {
                return ResourceManager.GetString("easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;A farmer kept track of his cows and hens by counting the legs and heads. If he counted 78 legs and 35 heads, how many cows did he have? &quot;,4
        ///&quot;If 7 men can do a job in 6 days, how many men can do the work in 3 days? &quot;,14
        ///&quot;If 4 workers can finish a job in 6 hours, what hours will it take for 6 workers to finish the same job? &quot;,4
        ///How many positive integers less than 1000 are divisible by either 5 or 13?,261
        ///Gemma can type 350 words in 5 minutes. How many words can she type in ¾ of an hour? ,3150
        ///Chester w [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string moderate {
            get {
                return ResourceManager.GetString("moderate", resourceCulture);
            }
        }
    }
}
